name: Playwright Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install playwright

      - name: Run Playwright Tests
        run: npx playwright test validation/ || true  # Continue even if tests fail

      - name: Generate README Update
        run: node validation/update-readme-loading.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update loading test results in README" || exit 0
          git push
