name: Validate Questionnaires

on:
  push:
    paths:
      - "questionnaires.js"  # Runs when questionnaire file changes
      - "validation/questionnaires/validate_questionnaires.js"  # Or when validation file changes
  workflow_dispatch:  # Allows manual triggering

jobs:
  validate:
    runs-on: ubuntu-24.04 # Latest LTS version of Ubuntu
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checks out your repository

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use LTS version of Node.js

      - name: Run Validation Script
        run: node validation/questionnaires/validate_questionnaires.js

      - name: Upload HTML Table as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: questionnaire_table  # Name of the artifact
          path: questionnaire_table.html  # Path to the generated file
