name: Validate Questionnaires

on:
  push:
    paths:
      - "questionnaires.js"  # Runs when questionnaire file changes
      - "validation/questionnaires/validate_questionnaires.js"  # Or when validation file changes
  workflow_dispatch:  # Allows manual triggering

jobs:
  validate:
    runs-on: ubuntu-24.04 # Latest LTS version of Ubuntu
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checks out your repository

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use LTS version of Node.js

      - name: Run Validation Script
        run: node validation/questionnaires/validate_questionnaires.js

      - name: Upload HTML Table as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: questionnaire_table  # Name of the artifact
          path: questionnaire_table.html  # Path to the generated file
      
      - name: Replace validation report in README
        run: |
          # Find the start and end markers for the report in the README
          START_MARKER="<!-- START Validation Report -->"
          END_MARKER="<!-- END Validation Report -->"

          # If markers exist, replace content between them
          if grep -q "$START_MARKER" README.md; then
            awk -v start="$START_MARKER" -v end="$END_MARKER" '
              $0 ~ start {print; while (getline && $0 !~ end) {}}
              $0 ~ end {print ""; system("cat report.html"); print; next}
              {print}
            ' README.md > temp.md && mv temp.md README.md
          else
            # If markers do not exist, append them
            echo -e "\n$START_MARKER" >> README.md
            cat report.html >> README.md
            echo -e "\n$END_MARKER" >> README.md
          fi
                    
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with latest validation report"
          git push
